### PR TITLE
updated description to improve consistency between wallets

### PR DESCRIPTION
**Pull request by kristovatlas**

### CODE REVIEW

**Comment by kristovatlas** [comment]
@justusranvier please review and merge pull request

**Comment by justusranvier** [comment]
What's your source for "Dark Wallet" being more correct than "Darkwallet"?

**Comment by kristovatlas** [comment]
none

**Comment by justusranvier** [comment]
Based on this, and what's displayed in the app itself, I think "Darkwallet" is correct:

https://www.darkwallet.is/

**Comment by kristovatlas** [comment]
updated wallet name

**Pull request merged**
